### ISSUE TITLE
music is not working

### ISSUE THREAD

**Issue by therealvkr** [normanlol/vidpolaris-rw#3]
hi 
music is not working .. 
https://vidpolaris.tube/music/ 
it just show a message please wait .. 
![Screenshot_2021-01-28-22-55-04-351_com android chrome](https://user-images.githubusercontent.com/62456443/106175258-e8f3c300-61bb-11eb-828d-567c62224c09.jpg)

**Comment by normanlol** [comment]
thanks for letting me know, resolving the issue right now!

**Comment by normanlol** [comment]
found it pretty easily, just a small little oversight!
